server:
  port: 8009

spring:
  datasource:
    url: jdbc:mysql://120.53.2.251:3306/hotel?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Ruifeng0328!


